CREATE TABLE IF NOT EXISTS arc
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rc BIGINT UNSIGNED NOT NULL,
    ar BIGINT UNSIGNED NOT NULL,
    v BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(rc) REFERENCES rc(id), 
    FOREIGN KEY(ar) REFERENCES ar(id), 
    FOREIGN KEY(v) REFERENCES v(id),
    UNIQUE(rc, ar) 
);
    