CREATE TABLE IF NOT EXISTS arco
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rco BIGINT UNSIGNED NOT NULL,
    arc BIGINT UNSIGNED NOT NULL,
    v BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(rco) REFERENCES rco(id), 
    FOREIGN KEY(arc) REFERENCES arc(id), 
    FOREIGN KEY(v) REFERENCES v(id),
    UNIQUE(rco, arc) 
);