CREATE TABLE IF NOT EXISTS co
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    c INT NOT NULL,
    o INT NOT NULL,
    FOREIGN KEY(c) REFERENCES c(id), 
    FOREIGN KEY(o) REFERENCES o(id),
    UNIQUE(c, o) 
)  ENGINE=INNODB;
 