CREATE TABLE IF NOT EXISTS ac
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    c BIGINT UNSIGNED NOT NULL,
    a BIGINT UNSIGNED NOT NULL,
    v BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(c) REFERENCES c(id), 
    FOREIGN KEY(a) REFERENCES a(id), 
    FOREIGN KEY(v) REFERENCES v(id),
    UNIQUE(c, a) 
);
  