CREATE TABLE IF NOT EXISTS rco
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rc BIGINT UNSIGNED NOT NULL,
    cof BIGINT UNSIGNED NOT NULL,
    cot BIGINT UNSIGNED NOT NULL,
    i BIGINT UNSIGNED  NOT NULL DEFAULT 0,
    FOREIGN KEY(rc) REFERENCES rc(id), 
    FOREIGN KEY(cof) REFERENCES co(id), 
    FOREIGN KEY(cot) REFERENCES co(id),
    UNIQUE(rc, cof, cot, i) 
);
  