CREATE TABLE IF NOT EXISTS rc
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    r BIGINT UNSIGNED NOT NULL,
    cf BIGINT UNSIGNED NOT NULL,
    ct BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(r) REFERENCES r(id), 
    FOREIGN KEY(cf) REFERENCES c(id), 
    FOREIGN KEY(ct) REFERENCES c(id),
    UNIQUE(r, cf, ct) 
)
    