CREATE TABLE IF NOT EXISTS ar
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    r BIGINT UNSIGNED NOT NULL,
    a BIGINT UNSIGNED NOT NULL,
    v BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(r) REFERENCES r(id), 
    FOREIGN KEY(a) REFERENCES a(id), 
    FOREIGN KEY(v) REFERENCES v(id),
    UNIQUE(r, a) 
);
  