CREATE TABLE IF NOT EXISTS RCO
(
    id INTEGER PRIMARY KEY,
    rc INTEGER NOT NULL,
    of INTEGER NOT NULL,
    ot INTEGER NOT NULL,
    FOREIGN KEY(rc) REFERENCES RC(id), 
    FOREIGN KEY(of) REFERENCES O(id), 
    FOREIGN KEY(ot) REFERENCES O(id),
    UNIQUE(rc, of, ot) 
)
    