CREATE TABLE IF NOT EXISTS RCO
(
    id BIGINT PRIMARY KEY,
    rc BIGINT NOT NULL,
    of BIGINT NOT NULL,
    ot BIGINT NOT NULL,
    FOREIGN KEY(rc) REFERENCES RC(id), 
    FOREIGN KEY(of) REFERENCES O(id), 
    FOREIGN KEY(ot) REFERENCES O(id),
    UNIQUE(rc, of, ot) 
)
    