CREATE TABLE IF NOT EXISTS AR
(
    id BIGINT PRIMARY KEY,
    r BIGINT NOT NULL,
    a BIGINT NOT NULL,
    v BIGINT NOT NULL,
    FOREIGN KEY(r) REFERENCES R(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(r, a) 
)
    