CREATE TABLE IF NOT EXISTS ACO
(
    id BIGINT PRIMARY KEY,
    co BIGINT NOT NULL,
    a BIGINT NOT NULL,
    v BIGINT NOT NULL,
    FOREIGN KEY(co) REFERENCES CO(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(co, a) 
)
    