CREATE TABLE IF NOT EXISTS RC
(
    id BIGINT PRIMARY KEY,
    r BIGINT NOT NULL,
    cf BIGINT NOT NULL,
    ct BIGINT NOT NULL,
    FOREIGN KEY(r) REFERENCES R(id), 
    FOREIGN KEY(cf) REFERENCES C(id), 
    FOREIGN KEY(ct) REFERENCES C(id),
    UNIQUE(r, cf, ct) 
)
    