CREATE TABLE IF NOT EXISTS ARC
(
    id BIGINT PRIMARY KEY,
    rc BIGINT NOT NULL,
    a BIGINT NOT NULL,
    v BIGINT NOT NULL,
    FOREIGN KEY(rc) REFERENCES RC(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(rc, a) 
)
    