CREATE TABLE IF NOT EXISTS ARCO
(
    id INTEGER PRIMARY KEY,
    rco INTEGER NOT NULL,
    a INTEGER NOT NULL,
    v INTEGER NOT NULL,
    FOREIGN KEY(rco) REFERENCES RCO(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(rco, a, v) 
)
    