CREATE TABLE IF NOT EXISTS AC
(
    id INTEGER PRIMARY KEY,
    c INTEGER NOT NULL,
    a INTEGER NOT NULL,
    v INTEGER NOT NULL,
    FOREIGN KEY(c) REFERENCES C(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(c, a, v) 
)
    