CREATE TABLE IF NOT EXISTS RC
(
    id INTEGER PRIMARY KEY,
    r INTEGER NOT NULL,
    cf INTEGER NOT NULL,
    ct INTEGER NOT NULL,
    FOREIGN KEY(r) REFERENCES R(id), 
    FOREIGN KEY(cf) REFERENCES C(id), 
    FOREIGN KEY(ct) REFERENCES C(id),
    UNIQUE(r, cf, ct) 
)
    