CREATE TABLE IF NOT EXISTS CO
(
    id BIGINT PRIMARY KEY,
    c BIGINT NOT NULL,
    o BIGINT NOT NULL,
    FOREIGN KEY(c) REFERENCES C(id), 
    FOREIGN KEY(o) REFERENCES O(id),
    UNIQUE(c, o) 
)
    