CREATE TABLE IF NOT EXISTS AC
(
    id BIGINT PRIMARY KEY,
    c BIGINT NOT NULL,
    a BIGINT NOT NULL,
    v BIGINT NOT NULL,
    FOREIGN KEY(c) REFERENCES C(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(c, a) 
)
    