CREATE TABLE IF NOT EXISTS CO
(
    id INTEGER PRIMARY KEY,
    c INTEGER NOT NULL,
    o INTEGER NOT NULL,
    FOREIGN KEY(c) REFERENCES C(id), 
    FOREIGN KEY(o) REFERENCES O(id),
    UNIQUE(c, o) 
)
    