CREATE TABLE IF NOT EXISTS ARCO
(
    id BIGINT PRIMARY KEY,
    rco BIGINT NOT NULL,
    a BIGINT NOT NULL,
    v BIGINT NOT NULL,
    FOREIGN KEY(rco) REFERENCES RCO(id), 
    FOREIGN KEY(a) REFERENCES A(id), 
    FOREIGN KEY(v) REFERENCES V(id),
    UNIQUE(rco, a) 
)
    